Get media details script; refs: ARC-8275
- added script and readme
- created get_standard_arguments util function, so we copy-paste less
- added argument check to bin/run

Full Jira ticket reference:
https://instructure.atlassian.net/browse/ARC-8275

diff --git a/bin/run b/bin/run
--- a/bin/run
+++ b/bin/run
@@ -19,4 +19,10 @@ fi
 script_path="${1}"
 shift
 
+if [ ! -f "${script_path}" ]; then
+  echo "Error: ${script_path} is not a file. Please specify a Python script to run."
+  echo "Usage: bin/run <script_path>"
+  exit 1
+fi
+
 PYTHONPATH="${__dir}" exec python "${script_path}" "$@"
